api = "0.9"

[buildpack]
  id = "bincraft/mesonpack"
  name = "Meson Buildpack"
  version = "0.1.0"
  description = "Cloud Native Buildpack for C and C++ with Meson"

[[targets]]
  os = "darwin"
  arch = "amd64"

[[targets]]
  os = "darwin"
  arch = "arm64"

[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"

[[stacks]]
  id = "net.binarycraft.stacks.hera"
